version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build:
      context:
        ../backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context:
        ../frontend
    volumes:
      - ./frontend/:/app/result_build/


  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/

      - /etc/letsencrypt/:/etc/letsencrypt

      - ./docs/redoc/:/usr/share/nginx/html/api/docs/redoc/
      - ./docs/:/usr/share/nginx/html/api/docs/

      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
      - db
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value:

