# Generated by Django 2.2.16 on 2022-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220314_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='in_card',
        ),
        migrations.AddField(
            model_name='recipe',
            name='in_cart',
            field=models.ManyToManyField(related_name='cart', to='recipes.Recipe', verbose_name='В корзине'),
        ),
    ]
