# Generated by Django 2.2.16 on 2022-03-14 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20220314_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='in_cart',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='В корзине'),
        ),
    ]
