# Generated by Django 2.2.16 on 2022-03-14 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220314_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='count',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Избранное'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='in_cart',
            field=models.ManyToManyField(related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='В корзине'),
        ),
    ]
