# Generated by Django 2.2.16 on 2022-03-10 22:53

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, validators=[django.contrib.auth.password_validation.validate_password], verbose_name='Паспорт'),
        ),
    ]
